language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: 4.4
script:
- npm run lint
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_358d96fd53b7_key -iv $encrypted_358d96fd53b7_iv -in .env.enc -out .env -d
env:
  global:
  - CF_APP=watsondevday-ams
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=edward_ciggaar@nl.ibm.com
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: eciggaar/text-bot
  skip_cleanup: true
